// All bilingual content strings
const CONTENT = {
  en: {
    nav: { home: "Home", about: "About", work: "Work", skills: "Skills", creds: "Credentials", contact: "Contact", toggle: "العربية" },
    hero: {
      badge: "Available July 2026",
      name: "Mohammed Aldkhily",
      roles: ["Full-Stack Developer", "AI Engineer", "CS Senior", "Building Real Systems"],
      desc: "Senior Computer Science student specializing in Artificial Intelligence and Machine Learning, with a growing focus on AI agent systems and modern AI patterns such as RAG, agentic workflows, and MCP. I build practical AI-driven applications and complement my AI work with full-stack development skills to deliver complete, production-ready solutions.",
      cta1: "View Work",
      cta2: "Download CV",
      scroll: "Scroll to explore",
    },
    about: {
      eyebrow: "1 — About",
      title: "About",
      body: "I'm a final-year Computer Science student at Qassim University, graduating in June 2026. I focus on building software that connects modern AI capabilities to real-world use cases. Over the past two years I've shipped a bilingual medical NLP platform, a Saudi-market e-commerce store, and an MCP-powered AI agent that controls real IoT devices. I care about clean code, fast load times, and systems that actually work in production. Looking for a Co-Op or full-time role where I can build meaningful technical work alongside a strong team.",
      stats: [
        { n: 3, suf: "+", label: "Production Projects" },
        { n: 12, suf: "", label: "Certifications" },
        { n: 2, suf: "",  label: "Languages · AR · EN", isLang: true },
      ],
      location: "Riyadh, Saudi Arabia",
      available: "Available July 2026",
    },
    work: {
      eyebrow: "2 — Selected Work",
      title: "Selected Work",
      subtitle: "Five projects I've shipped that solve real problems.",
      latest: "LATEST",
      live: "Live Demo",
      code: "Code",
      projects: [
        {
          tag: "COMPUTER VISION · 2026",
          title: "Qassim Food Detection",
          summary: "Real-time computer vision system that recognizes traditional Qassim dishes from images and live video.",
          desc: "A YOLO-based detection system trained to identify traditional dishes from the Qassim region. The pipeline covers data collection, deduplication, pixel-precise labeling with SAM 3, training, and ONNX deployment for real-time inference on a live webcam feed.",
          achievements: [
            { icon: "Target",   text: "YOLO11x with 57M parameters fine-tuned on a custom dataset" },
            { icon: "Tag",      text: "Pixel-precise labeling using Roboflow + Meta SAM 3" },
            { icon: "Filter",   text: "pHash deduplication to prevent train/validation data leakage" },
            { icon: "Zap",      text: "Real-time inference at 53 FPS via ONNX FP16 export" },
          ],
          tech: ["Python", "PyTorch", "YOLO11", "Ultralytics", "ONNX", "OpenCV"],
          kind: "qassim",
          reverse: false,
          featured: true,
          github: "https://github.com/iMDK-cs/qassim-food-detection",
        },
        {
          tag: "AI / RAG · 2026",
          title: "Mundial Chatbot",
          summary: "Bilingual RAG assistant for FIFA World Cup 2026 — fine-tuned LLM with anti-hallucination guardrails.",
          desc: "End-to-end AI system combining fine-tuning, retrieval-augmented generation, and a production API — all focused on the 2026 World Cup. Fine-tuned Mistral-7B (4-bit QLoRA) on 6,949 bilingual Q&A pairs (Arabic + English + Saudi dialect) that I synthetically generated using the Anthropic API, then deployed behind a multilingual RAG pipeline with FastAPI + SSE streaming and a 4-layer routing system that keeps hallucinations out.",
          achievements: [
            { icon: "Cpu",         text: "Fine-tuned Mistral-7B with QLoRA on 6,949 bilingual Q&A pairs (~73 min, 2 epochs on RTX 3080)" },
            { icon: "Database",    text: "Multilingual MiniLM retriever over 7,158 indexed chunks; threshold-gated at 0.55 to block weak matches" },
            { icon: "ShieldCheck", text: "95% benchmark accuracy with 100% out-of-scope refusal; greedy decoding + regex post-filter against hallucination" },
            { icon: "Zap",         text: "FastAPI + SSE streaming on Hugging Face Spaces; TTFT p50 = 2.04s" },
          ],
          tech: ["Python", "PyTorch", "Mistral-7B", "QLoRA", "PEFT", "TRL", "FastAPI", "Hugging Face"],
          kind: "worldcup",
          reverse: false,
          live: "https://huggingface.co/spaces/iMDk-CS/worldcup-rag-chatbot",
          github: "https://github.com/iMDk-cs/worldcup-rag-chatbot",
        },
        {
          tag: "GRADUATION PROJECT · 2026",
          title: "Medical Diagnosis Platform",
          summary: "Bilingual healthcare platform that turns patient symptoms into structured medical reports.",
          desc: "A web platform that automates patient intake before consultations. Patients describe their symptoms in free-text Arabic or English; an NLP layer powered by GPT analyzes the input and generates a structured medical report for the doctor. Includes role-based access for patients, doctors, and admins.",
          achievements: [
            { icon: "Globe", text: "Bilingual interface (Arabic + English) with NLP-driven symptom parsing" },
            { icon: "Users", text: "Role-based access for patients, doctors, and admins" },
            { icon: "TrendingUp", text: "95% user satisfaction in usability testing" },
            { icon: "Shield", text: "Secure data layer using Drizzle ORM and Neon Postgres" },
          ],
          tech: ["Next.js", "TypeScript", "OpenAI API", "Drizzle ORM", "Neon", "Tailwind"],
          kind: "medical",
          reverse: false,
        },
        {
          tag: "PERSONAL PROJECT · 2025",
          title: "SmoothFlow",
          summary: "Production-ready PC store built solo for the Saudi market.",
          desc: "Full-stack e-commerce platform for selling PC components. Built solo, end-to-end. Features secure JWT authentication, integrated Paymob payment gateway for Saudi customers, rate limiting, and security hardening. Deployed on Vercel with automated CI/CD.",
          achievements: [
            { icon: "Zap", text: "Sub-2-second page loads on 98% of requests" },
            { icon: "Lock", text: "JWT-based authentication with NextAuth" },
            { icon: "CreditCard", text: "Paymob payment gateway integration (Saudi market)" },
            { icon: "ShieldCheck", text: "Production security headers and rate limiting" },
          ],
          tech: ["Next.js 15", "TypeScript", "Prisma", "PostgreSQL", "NextAuth", "Paymob", "Vercel"],
          kind: "store",
          reverse: true,
          live: "https://smoothflow-sa.vercel.app/",
          github: "https://github.com/iMDK-cs/SmoothFLow-Store",
        },
        {
          tag: "PERSONAL PROJECT · 2026",
          title: "AI Agent Smart Home Assistant",
          summary: "Telegram AI agent controlling real IoT devices via MCP.",
          desc: "An AI Telegram bot that controls real-world smart home devices through natural language. Built on MCP — the emerging open standard for AI agent tool integration. The MCP server exposes Tuya Cloud IoT controls (lights, climate, appliances) as agent-callable tools, while Google Gemini handles reasoning and intent parsing in both Arabic and English.",
          img: "uploads/n8n.jpg",
          achievements: [
            { icon: "Cpu", text: "Implemented MCP Server exposing IoT controls as agent tools" },
            { icon: "Globe", text: "Bilingual NLU — handles AR and EN commands seamlessly" },
            { icon: "Clock", text: "~4-second average end-to-end response time" },
            { icon: "MessageSquare", text: "Persistent multi-turn conversation memory" },
          ],
          tech: ["n8n", "MCP", "Google Gemini", "Tuya IoT Cloud", "Telegram Bot API"],
          kind: "telegram",
          reverse: false,
        },
      ],
    },
    skills: {
      eyebrow: "4 — Toolbox",
      title: "Toolbox",
      subtitle: "Tech I use to build.",
      cats: [
        { icon: "Code2",    name: "Languages",        items: ["TypeScript","JavaScript","Python","C++","SQL"] },
        { icon: "Layout",   name: "Frontend",         items: ["Next.js","React","Tailwind CSS","HTML5","CSS3"] },
        { icon: "Server",   name: "Backend",          items: ["Node.js","REST APIs","NextAuth","JWT"] },
        { icon: "Database", name: "Databases",        items: ["PostgreSQL","Prisma","Drizzle","Neon"] },
        { icon: "Cpu",      name: "AI & Automation",  items: ["OpenAI API","Google Gemini","MCP","n8n","NLP"] },
        { icon: "Sparkles", name: "AI/ML Algorithms", items: ["Supervised Learning","NLP","Embeddings","Prompt Engineering","RAG"] },
        { icon: "Server",   name: "System Administration", items: ["Linux","Bash","Networking","Deployment","Monitoring"] },
        { icon: "Wrench",   name: "DevOps & Tools",   items: ["Git","GitHub","Vercel","Postman"] },
      ],
    },
    creds: {
      eyebrow: "3 — Credentials",
      title: "Credentials",
      eduLabel: "Education",
      certLabel: "Certifications",
      degree: "Bachelor's in Computer Science",
      university: "Qassim University",
      years: "2021 – 2026",

      certs: [
        { name: "Artificial Intelligence Concepts and Advanced Applications", org: "SDAIA",     img: "uploads/Artificial Intelligence Concepts and Advanced Application.png", file: "uploads/Artificial Intelligence Concepts and Advanced Application.png" },
        { name: "Fundamentals of Artificial Intelligence",                    org: "SDAIA",     img: "uploads/Fundamentals of Artificial Intelligence.png", file: "uploads/Fundamentals of Artificial Intelligence.png" },
        { name: "Advanced AI and Machine Learning Techniques and Capstone",   org: "Microsoft", img: "uploads/Advanced AI and Machine Learning Techniques and Capstone.png",             file: "uploads/Advanced AI and Machine Learning Techniques and Capstone.png" },
        { name: "Foundations of AI and Machine Learning",                     org: "Microsoft", img: "uploads/Foundations of AI and Machine Learning.png", file: "uploads/Foundations of AI and Machine Learning.png" },
        { name: "Advanced RAG with Vector Databases and Retrievers",          org: "IBM",       img: "uploads/Advanced RAG with Vector Databases and Retrievers.png",                   file: "uploads/Advanced RAG with Vector Databases and Retrievers.png" },
        { name: "Agentic AI with LangChain and LangGraph",                    org: "IBM",       img: "uploads/Agentic AI with LangChain and LangGraph.png",                            file: "uploads/Agentic AI with LangChain and LangGraph.png" },
        { name: "RAG and Agentic AI Capstone Project",                        org: "IBM",       img: "uploads/IBM RAG and Agentic AI.png", file: "uploads/IBM RAG and Agentic AI.png" },
        { name: "Build AI Agents using MCP",                                  org: "IBM",       img: "uploads/Build AI Agents using MCP.png",                                          file: "uploads/Build AI Agents using MCP.png" },
        { name: "Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI",       org: "IBM",       img: "uploads/Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI.png",               file: "uploads/Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI.png" },
        { name: "Fundamentals of Building AI Agents",                         org: "IBM",       img: "uploads/Fundamentals of Building AI Agents.png",                                 file: "uploads/Fundamentals of Building AI Agents.png" },
        { name: "Build Multimodal Generative AI Applications",                org: "IBM",       img: "uploads/Build Multimodal Generative AI Applications.png",                        file: "uploads/Build Multimodal Generative AI Applications.png" },
        { name: "Data Analysis",                                              org: "MISK",      img: "uploads/thlyl-albyanat-certificate.png", file: "uploads/thlyl-albyanat-certificate.png" },
      ],
    },
    contact: {
      eyebrow: "5 — Contact",
      title: "Contact info",
      subtitle: "Open to Co-Op and full-time roles starting July 2026. Drop me a line.",
      cards: [
        { icon: "Mail", label: "Email", value: "mohammed.aldkhily@gmail.com", href: "mailto:mohammed.aldkhily@gmail.com" },
        { icon: "Phone", label: "Phone", value: "+966 54 315 6466", href: "tel:+966543156466" },
        { icon: "Github", label: "GitHub", value: "github.com/imdk-cs", href: "https://github.com/imdk-cs" },
        { icon: "Linkedin", label: "LinkedIn", value: "linkedin.com/in/mohammed-cs0", href: "https://www.linkedin.com/in/mohammed-cs0/" },
      ],
    },
    footer: {
      line1: "Designed and built by Mohammed Aldkhily — 2026",
      line2: "Built with React and Tailwind CSS",
    },
    // Visual mockup strings
    mock: {
      medicalBrowser: "medical-platform.app",
      medicalInputLabel: "Patient Input · AR",
      medicalInput: "أعاني من صداع شديد منذ يومين، مع حرارة خفيفة ودوخة عند الوقوف.",
      medicalReportLabel: "Generated Report · EN",
      medicalReport: [
        { k: "Symptom",  v: "Headache, mild fever, orthostatic dizziness" },
        { k: "Duration", v: "2 days" },
        { k: "Severity", v: "Moderate" },
        { k: "Triage",   v: "Primary care — non-urgent" },
      ],
      storeBrowser: "smoothflow.sa",
      storeCat: "PC Components",
      storeProducts: [
        { name: "RTX 4080 Super",  price: "4,899 SAR", tag: "GPU" },
        { name: "Ryzen 9 7950X",   price: "2,649 SAR", tag: "CPU" },
        { name: "32GB DDR5 6000",  price: "  649 SAR", tag: "RAM" },
        { name: "2TB NVMe Gen4",   price: "  549 SAR", tag: "SSD" },
      ],
      addToCart: "Add to cart",
      telegramTitle: "Smart Home Agent",
      telegramOnline: "online",
      telegramMessages: [
        { from: "user", text: "شغّل إضاءة الصالة" },
        { from: "bot",  text: "تم تشغيل إضاءة الصالة." },
        { from: "user", text: "Set the AC to 21°C" },
        { from: "bot",  text: "AC set to 21°C. Living room climate control updated." },
      ],
      archFlow: ["User","Telegram","n8n","MCP","Tuya","Device"],
    },
  },
  ar: {
    nav: { home: "الرئيسية", about: "عني", work: "الأعمال", skills: "المهارات", creds: "الشهادات", contact: "تواصل", toggle: "EN" },
    hero: {
      badge: "متاح من يوليو 2026",
      name: "محمد الدخيلي",
      roles: ["مطوّر Full-Stack", "مهندس AI", "طالب علوم حاسب", "أبني أنظمة حقيقية"],
      desc: "طالب علوم حاسب مهتم بمجال الذكاء الاصطناعي والتقنيات الجديده واركز على تعلم الاشياء الجديدة — تعلم الآلة والـ AI Agent و RAG و MCP. وعندي خلفية عن تطوير وبناء المواقع.",
      cta1: "شوف الأعمال",
      cta2: "حمّل السيرة الذاتية",
      scroll: "اسحب لتشوف أكثر",
    },
    about: {
      eyebrow: "1 — عني",
      title: "عني",
      body: "أنا طالب علوم حاسب اخر ترم في جامعة القصيم، شغال على بناء أنظمة تربط بين الذكاء الاصطناعي الحديث واستخدامات فعلية على أرض الواقع. آخر سنتين بنيت منصة طبية ثنائية اللغة بالـ NLP، متجر إلكتروني للسوق السعودي، ومساعد AI شغّال بالـ MCP يتحكم بأجهزة IoT حقيقية. مهتم بالكود النظيف، سرعة التحميل، والأنظمة الي فعلاً تشتغل في الإنتاج. أدور عن Co-Op أو وظيفة full-time أقدر فيها أشتغل على شي تقني له قيمة مع فريق قوي.",
      stats: [
        { n: 3, suf: "+", label: "مشاريع شغّالة" },
        { n: 12, suf: "", label: "شهادات احترافية" },
        { n: 2, suf: "",  label: "ثنائي اللغة · عربي · إنجليزي", isLang: true },
      ],
      location: "الرياض، السعودية",
      available: "متاح من يوليو 2026",
    },
    work: {
      eyebrow: "2 — أعمال مختارة",
      title: "أعمال مختارة",
      subtitle: "خمسة مشاريع طلّعتها للنور وكلها تحل مشكلة فعلية.",
      latest: "الأحدث",
      live: "تجربة مباشرة",
      code: "الكود",
      projects: [
        {
          tag: "رؤية حاسوبية · 2026",
          title: "Qassim Food Detection",
          summary: "نظام رؤية حاسوبية لحظي يتعرّف على الأكلات التراثية من منطقة القصيم من الصور والفيديو المباشر.",
          desc: "نظام كشف مبني على YOLO مدرّب على التعرّف على الأكلات التراثية من منطقة القصيم. الـ pipeline يغطي جمع البيانات، إزالة المكرر، التوسيم الدقيق على مستوى البكسل بـ SAM 3، التدريب، ثم النشر على ONNX للتشغيل اللحظي على كاميرا حية.",
          achievements: [
            { icon: "Target",   text: "نموذج YOLO11x بـ 57M parameter مدرّب على Dataset مخصص" },
            { icon: "Tag",      text: "توسيم دقيق على مستوى البكسل عبر Roboflow + Meta SAM 3" },
            { icon: "Filter",   text: "إزالة المكرر بـ pHash لتفادي تسريب البيانات بين التدريب والتقييم" },
            { icon: "Zap",      text: "تشغيل لحظي بسرعة 53 FPS عبر تصدير ONNX بدقة FP16" },
          ],
          tech: ["Python", "PyTorch", "YOLO11", "Ultralytics", "ONNX", "OpenCV"],
          kind: "qassim",
          reverse: true,
          featured: true,
          github: "https://github.com/iMDK-cs/qassim-food-detection",
        },
        {
          tag: "AI / RAG · 2026",
          title: "Mundial Chatbot",
          summary: "مساعد RAG ثنائي اللغة لكأس العالم 2026 — موديل مُدرَّب مخصّص مع حماية ضد الهلوسة.",
          desc: "نظام AI كامل يجمع بين الـ Fine-tuning و RAG و API جاهز للإنتاج، كله مركّز على كأس العالم 2026. درّبت Mistral-7B بـ QLoRA على 6,949 سؤال وجواب ثنائي اللغة (عربي + إنجليزي + لهجة سعودية) ولّدتها synthetically عبر Anthropic API، ونشرته خلف pipeline متعدد اللغات بـ FastAPI و SSE streaming، مع بنية routing من 4 طبقات تمنع الهلوسة.",
          achievements: [
            { icon: "Cpu",         text: "تدريب Mistral-7B بـ QLoRA على 6,949 سؤال وجواب ثنائي اللغة (~73 دقيقة، 2 epochs على RTX 3080)" },
            { icon: "Database",    text: "Retriever متعدد اللغات بـ MiniLM على 7,158 chunk مفهرسة، مع حد ثقة 0.55 لرفض الإجابات الضعيفة" },
            { icon: "ShieldCheck", text: "دقة 95% على benchmark مع 100% رفض للأسئلة خارج النطاق، و greedy decoding + regex post-filter ضد الهلوسة" },
            { icon: "Zap",         text: "FastAPI + SSE streaming على Hugging Face Spaces؛ TTFT p50 = 2.04 ثانية" },
          ],
          tech: ["Python", "PyTorch", "Mistral-7B", "QLoRA", "PEFT", "TRL", "FastAPI", "Hugging Face"],
          kind: "worldcup",
          reverse: false,
          live: "https://huggingface.co/spaces/iMDk-CS/worldcup-rag-chatbot",
          github: "https://github.com/iMDk-cs/worldcup-rag-chatbot",
        },
        {
          tag: "مشروع التخرج · 2026",
          title: "منصة التشخيص الطبي",
          summary: "منصة طبية ثنائية اللغة تحوّل أعراض المريض لتقرير طبي مهيكل.",
          desc: "منصة ويب تأتمت استقبال المرضى قبل الكشف. المريض يكتب أعراضه بنص حر بالعربي أو الإنجليزي، وطبقة NLP مبنية على GPT تحلل الكلام وتطلّع تقرير طبي منظّم للدكتور. فيها صلاحيات مختلفة للمرضى والأطباء والمشرفين.",
          achievements: [
            { icon: "Globe", text: "واجهة ثنائية اللغة (عربي + إنجليزي) مع NLP يحلل وصف الأعراض" },
            { icon: "Users", text: "صلاحيات وصول للمرضى والأطباء والمشرفين" },
            { icon: "TrendingUp", text: "95% رضا مستخدمين في اختبارات الاستخدام" },
            { icon: "Shield", text: "طبقة بيانات آمنة باستخدام Drizzle ORM و Neon Postgres" },
          ],
          tech: ["Next.js", "TypeScript", "OpenAI API", "Drizzle ORM", "Neon", "Tailwind"],
          kind: "medical",
          reverse: false,
        },
        {
          tag: "مشروع شخصي · 2025",
          title: "SmoothFlow",
          summary: "متجر مكونات كمبيوتر بُني من الصفر لحالي للسوق السعودي.",
          desc: "منصة تجارة إلكترونية كاملة لبيع مكونات الكمبيوتر. بنيتها لحالي من الـA للـZ. فيها نظام تسجيل دخول JWT آمن، تكامل مع Paymob للدفع للعملاء السعوديين، حماية ضد الطلبات الكثيرة، وأمان كامل. منشورة على Vercel مع CI/CD تلقائي.",
          achievements: [
            { icon: "Zap", text: "تحميل الصفحات أقل من ثانيتين لـ 98% من الطلبات" },
            { icon: "Lock", text: "تسجيل دخول آمن بـ JWT و NextAuth" },
            { icon: "CreditCard", text: "تكامل كامل مع بوابة Paymob للسوق السعودي" },
            { icon: "ShieldCheck", text: "حماية احترافية وتقييد طلبات" },
          ],
          tech: ["Next.js 15", "TypeScript", "Prisma", "PostgreSQL", "NextAuth", "Paymob", "Vercel"],
          kind: "store",
          reverse: true,
          live: "https://smoothflow-sa.vercel.app/",
          github: "https://github.com/iMDK-cs/SmoothFLow-Store",
        },
        {
          tag: "مشروع شخصي · 2026",
          title: "مساعد المنزل الذكي",
          summary: "وكيل AI على تيليجرام يتحكم بأجهزة IoT حقيقية عبر MCP.",
          desc: "بوت تيليجرام ذكي يتحكم بأجهزة المنزل الذكي عبر أوامر بلغة طبيعية. مبني على MCP — المعيار المفتوح الجديد لربط وكلاء AI بالأدوات. الـ MCP server يعرض تحكم أجهزة Tuya Cloud (إضاءة، تكييف، أجهزة) كأدوات قابلة للاستدعاء من الوكيل، و Google Gemini يتولى الفهم والتحليل بالعربي والإنجليزي.",
          img: "uploads/n8n.jpg",
          achievements: [
            { icon: "Cpu", text: "بنيت MCP Server يعرض تحكم الأجهزة كأدوات للوكيل" },
            { icon: "Globe", text: "فهم ثنائي اللغة — يستوعب الأوامر بالعربي والإنجليزي" },
            { icon: "Clock", text: "متوسط زمن الاستجابة 4 ثواني تقريباً" },
            { icon: "MessageSquare", text: "ذاكرة محادثة تحفظ السياق بين الرسائل" },
          ],
          tech: ["n8n", "MCP", "Google Gemini", "Tuya IoT Cloud", "Telegram Bot API"],
          kind: "telegram",
          reverse: false,
        },
      ],
    },
    skills: {
      eyebrow: "4 — صندوق الأدوات",
      title: "صندوق الأدوات",
      subtitle: "الأدوات الي أشتغل فيها.",
      cats: [
        { icon: "Code2",    name: "لغات البرمجة", items: ["TypeScript","JavaScript","Python","C++","SQL"] },
        { icon: "Layout",   name: "Frontend",       items: ["Next.js","React","Tailwind CSS","HTML5","CSS3"] },
        { icon: "Server",   name: "Backend",        items: ["Node.js","REST APIs","NextAuth","JWT"] },
        { icon: "Database", name: "قواعد البيانات", items: ["PostgreSQL","Prisma","Drizzle","Neon"] },
        { icon: "Cpu",      name: "AI و الأتمتة",   items: ["OpenAI API","Google Gemini","MCP","n8n","NLP"] },
        { icon: "Sparkles", name: "خوارزميات AI/ML", items: ["Supervised Learning","NLP","Embeddings","Prompt Engineering","RAG"] },
        { icon: "Server",   name: "إدارة الأنظمة",   items: ["Linux","Bash","Networking","Deployment","Monitoring"] },
        { icon: "Wrench",   name: "أدوات التطوير",  items: ["Git","GitHub","Vercel","Postman"] },
      ],
    },
    creds: {
      eyebrow: "3 — الشهادات والتعليم",
      title: "الشهادات والتعليم",
      eduLabel: "التعليم",
      certLabel: "الشهادات",
      degree: "بكالوريوس علوم حاسب",
      university: "جامعة القصيم",
      years: "2021 – 2026",

      certs: [
        { name: "Artificial Intelligence Concepts and Advanced Applications", org: "SDAIA",     img: "uploads/Artificial Intelligence Concepts and Advanced Application.png", file: "uploads/Artificial Intelligence Concepts and Advanced Application.png" },
        { name: "Fundamentals of Artificial Intelligence",                    org: "SDAIA",     img: "uploads/Fundamentals of Artificial Intelligence.png", file: "uploads/Fundamentals of Artificial Intelligence.png" },
        { name: "Advanced AI and Machine Learning Techniques and Capstone",   org: "Microsoft", img: "uploads/Advanced AI and Machine Learning Techniques and Capstone.png",             file: "uploads/Advanced AI and Machine Learning Techniques and Capstone.png" },
        { name: "Foundations of AI and Machine Learning",                     org: "Microsoft", img: "uploads/Foundations of AI and Machine Learning.png", file: "uploads/Foundations of AI and Machine Learning.png" },
        { name: "Advanced RAG with Vector Databases and Retrievers",          org: "IBM",       img: "uploads/Advanced RAG with Vector Databases and Retrievers.png",                   file: "uploads/Advanced RAG with Vector Databases and Retrievers.png" },
        { name: "Agentic AI with LangChain and LangGraph",                    org: "IBM",       img: "uploads/Agentic AI with LangChain and LangGraph.png",                            file: "uploads/Agentic AI with LangChain and LangGraph.png" },
        { name: "RAG and Agentic AI Capstone Project",                        org: "IBM",       img: "uploads/IBM RAG and Agentic AI.png", file: "uploads/IBM RAG and Agentic AI.png" },
        { name: "Build AI Agents using MCP",                                  org: "IBM",       img: "uploads/Build AI Agents using MCP.png",                                          file: "uploads/Build AI Agents using MCP.png" },
        { name: "Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI",       org: "IBM",       img: "uploads/Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI.png",               file: "uploads/Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI.png" },
        { name: "Fundamentals of Building AI Agents",                         org: "IBM",       img: "uploads/Fundamentals of Building AI Agents.png",                                 file: "uploads/Fundamentals of Building AI Agents.png" },
        { name: "Build Multimodal Generative AI Applications",                org: "IBM",       img: "uploads/Build Multimodal Generative AI Applications.png",                        file: "uploads/Build Multimodal Generative AI Applications.png" },
        { name: "Data Analysis",                                              org: "MISK",      img: "uploads/thlyl-albyanat-certificate.png", file: "uploads/thlyl-albyanat-certificate.png" },
      ],
    },
    contact: {
      eyebrow: "5 — تواصل",
      title: "خلّنا نبني شي.",
      subtitle: "متاح لـ Co-Op أو وظيفة full-time من يوليو 2026. راسلني.",
      cards: [
        { icon: "Mail", label: "البريد", value: "mohammed.aldkhily@gmail.com", href: "mailto:mohammed.aldkhily@gmail.com" },
        { icon: "Phone", label: "جوال", value: "+966 54 315 6466", href: "tel:+966543156466" },
        { icon: "Github", label: "GitHub", value: "github.com/imdk-cs", href: "https://github.com/imdk-cs" },
        { icon: "Linkedin", label: "LinkedIn", value: "linkedin.com/in/mohammed-cs0", href: "https://www.linkedin.com/in/mohammed-cs0/" },
      ],
    },
    footer: {
      line1: "صُمم وبُني بواسطة محمد الدخيلي — 2026",
      line2: "مبني بـ React و Tailwind CSS",
    },
    mock: {
      medicalBrowser: "medical-platform.app",
      medicalInputLabel: "إدخال المريض · عربي",
      medicalInput: "أعاني من صداع شديد منذ يومين، مع حرارة خفيفة ودوخة عند الوقوف.",
      medicalReportLabel: "التقرير المُولَّد · إنجليزي",
      medicalReport: [
        { k: "Symptom",  v: "Headache, mild fever, orthostatic dizziness" },
        { k: "Duration", v: "2 days" },
        { k: "Severity", v: "Moderate" },
        { k: "Triage",   v: "Primary care — non-urgent" },
      ],
      storeBrowser: "smoothflow.sa",
      storeCat: "مكونات الكمبيوتر",
      storeProducts: [
        { name: "RTX 4080 Super",  price: "4,899 ر.س", tag: "GPU" },
        { name: "Ryzen 9 7950X",   price: "2,649 ر.س", tag: "CPU" },
        { name: "32GB DDR5 6000",  price: "  649 ر.س", tag: "RAM" },
        { name: "2TB NVMe Gen4",   price: "  549 ر.س", tag: "SSD" },
      ],
      addToCart: "أضف للسلة",
      telegramTitle: "مساعد المنزل الذكي",
      telegramOnline: "متصل",
      telegramMessages: [
        { from: "user", text: "شغّل إضاءة الصالة" },
        { from: "bot",  text: "تم تشغيل إضاءة الصالة." },
        { from: "user", text: "خفّض التكييف على 21°م" },
        { from: "bot",  text: "تم ضبط التكييف على 21°م في الصالة." },
      ],
      archFlow: ["المستخدم","Telegram","n8n","MCP","Tuya","الجهاز"],
    },
  },
};

window.CONTENT = CONTENT;
